name: REALMFest
main: net.bunnehrealm.realmfest.RealmFest
version: 1.0
description: >
            Fun Commands!
commands:
  ride:
    description: Ride a player.
  rideme:
    description: Make a player ride you.
  bouquet:
    description: Make it rain with them flowers.
  smoke:
    description: Enable or Disable smoke trail.
  pvp:
    description: Enable or Disable PvP.
  shuriken:
    description: Throw your blades.
